name: GolNet
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  supabase_flutter: ^0.3.0
  mongo_dart: ^0.7.3
  uuid: ^3.0.4
  flutter_markdown: ^0.6.6
  shimmer: ^2.0.0
  animated_text_kit: ^4.2.2
  rive: ^0.7.0
  pin_code_fields: ^8.0.1
  form_field_validator: ^1.1.0
  flutter_reaction_button: ^3.0.0+3
  flutter_svg: ^2.0.9
  flutter_staggered_grid_view: ^0.4.0
  intro_slider: ^3.0.0
  cupertino_icons: ^1.0.2
  path_provider: ^2.1.3
  shared_preferences: ^2.0.8
  flutter_local_notifications: ^8.1.0
  like_button: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  table_calendar: ^3.0.9
  shared_preferences: ^2.0.8
  flutter_card_swipper: ^0.4.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icon/
