name: proyecto_portal_futbol
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1 # Asegúrate de tener esta línea
  supabase_flutter: ^2.4.0
  mongo_dart: ^0.10.1
  uuid: ^4.3.3
  flutter_markdown: ^0.7.1
  cupertino_icons: ^1.0.2
  pin_code_fields: 8.0.1
  animated_text_kit: ^4.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  table_calendar: ^3.0.9
  shared_preferences: ^2.0.8

flutter:
  uses-material-design: true
  assets:
    - assets/
